version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: syndic-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: syndic_db
      MYSQL_USER: chirinedb
      MYSQL_PASSWORD: "chirine@123"
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - syndic-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./backend
    container_name: syndic-backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=syndic_secret_key_2025
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=chirinedb
      - DB_PASSWORD=chirine@123
      - DB_NAME=syndic_db
    networks:
      - syndic-network
    restart: always

  frontend:
    build: ./frontend
    container_name: syndic-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:3001
    networks:
      - syndic-network
    restart: always

volumes:
  mysql_data:

networks:
  syndic-network:
    driver: bridge
